version: '3.8'

services:
  api:
    build:
      context: ../
      dockerfile: devops/Dockerfile
    image: fabrilos-api
    container_name: fabrilos-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
      - ConnectionStrings__DefaultConnection=Host=fabrilos-postgres;Port=5432;Database=fabrilos_db;Username=admin;Password=password;Include Error Detail=true
      - Minio__Endpoint=fabrilos-minio:9000
      - Minio__AccessKey=admin
      - Minio__SecretKey=password
      - Minio__BucketName=service-order-images
      - Minio__UseSSL=false
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    depends_on:
      - db
      - minio
    restart: on-failure
    networks:
      - fabrilos-network

  db:
    image: postgres:16
    container_name: fabrilos-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fabrilos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - fabrilos-network

  minio:
    image: minio/minio
    container_name: fabrilos-minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console Port
    volumes:
      - minio_data:/data
    restart: always
    networks:
      - fabrilos-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: fabrilos-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fabrilos.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always
    networks:
      - fabrilos-network

volumes:
  postgres_data:
  minio_data:
  pgadmin_data:

networks:
  fabrilos-network:
    driver: bridge